In [1]:
import numpy as np

In [2]:
X = np.array([[1,2], [3,4], [5,6], [7,8]])

In [3]:
# X = NxD matrix

# N = 4
# D = 2 

print X
print X.shape

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4L, 2L)


In [4]:
#W1 = DxM matrix
#D = 2
#M = 3

#W1 = np.array([[4,8,12], [3,6,9]])
W1 = np.random.rand(2,3)
print W1
print W1.shape

[[ 0.30728805  0.95180017  0.50719781]
 [ 0.43705258  0.18658956  0.06849195]]
(2L, 3L)


In [5]:
#b1 = Mx1 matrix
#M = 3


b1 = np.array([2,4,6])
print b1
print b1.shape

[2 4 6]
(3L,)


In [6]:
test = X.dot(W1)
test

array([[ 1.1813932 ,  1.3249793 ,  0.64418171],
       [ 2.67007444,  3.60175877,  1.79556122],
       [ 4.15875568,  5.87853825,  2.94694074],
       [ 5.64743692,  8.15531772,  4.09832026]])

In [7]:
test + b1

array([[  3.1813932 ,   5.3249793 ,   6.64418171],
       [  4.67007444,   7.60175877,   7.79556122],
       [  6.15875568,   9.87853825,   8.94694074],
       [  7.64743692,  12.15531772,  10.09832026]])

In [8]:
#Z will be a NxM matrix

#N = 4
#M = 3

Z = 1 / (1 + np.exp(-X.dot(W1) - b1))
print Z
print Z.shape

[[ 0.96012803  0.99515514  0.99870012]
 [ 0.99071544  0.99950068  0.99958861]
 [ 0.99788958  0.99994874  0.99986988]
 [ 0.99952296  0.99999474  0.99995885]]
(4L, 3L)


In [ ]:
W2 = np.random.rand(M,K)