Softmax Calculation 

Using an array and a matrix



In [1]:
import numpy as np

 Use Randn to return a sample (or samples) from the “standard normal” distribution.

In [2]:
a = np.random.randn(5)
a

array([-0.59270988, -0.671331  , -1.29670762,  0.14258024,  0.10853386])

Step 1: We want to exponentiate these. Remember we exponentiate to turn the elements positive

In [3]:
expa = np.exp(a)
expa

array([ 0.55282716,  0.51102795,  0.27343055,  1.15324561,  1.11464265])

Step 2: We want the answer to be each element divided by sum of elements

In [4]:
answer = expa / expa.sum()
answer

array([ 0.15334272,  0.14174849,  0.07584393,  0.31988626,  0.30917861])

The sum of answers should equal to 1

In [5]:
answer.sum()

1.0

Lets try this again with a matrix

In [6]:
A = np.random.rand(100,5) #This is 100 samples and 5 classes
A

array([[  9.25904356e-01,   5.50057034e-01,   5.49374915e-01,
          6.15293732e-01,   9.05485498e-01],
       [  3.46114847e-01,   8.76469274e-01,   8.02908462e-01,
          9.08608321e-01,   8.16836555e-01],
       [  5.02139330e-01,   6.25089969e-01,   1.47926203e-02,
          8.48528565e-01,   1.66975762e-01],
       [  4.83554491e-01,   9.33864124e-01,   4.15003153e-01,
          7.96780486e-01,   3.95488575e-01],
       [  4.61843843e-01,   3.68271927e-01,   4.81595847e-01,
          3.30574266e-01,   3.56079195e-01],
       [  7.90847985e-01,   1.10516817e-01,   9.96359489e-02,
          1.49303570e-02,   6.33876049e-01],
       [  4.48432585e-01,   7.11785784e-02,   1.73102252e-01,
          9.50105505e-01,   8.62179243e-01],
       [  6.73605378e-01,   9.14512184e-01,   4.83897266e-01,
          1.99589218e-01,   5.11986577e-01],
       [  6.77833176e-01,   3.95530787e-01,   9.53754988e-01,
          1.85234807e-01,   1.48053878e-01],
       [  7.57194794e-01,   8.6279307

In [7]:
expA = np.exp(A)
expA

array([[ 2.52414996,  1.73335187,  1.73216993,  1.85019998,  2.47313233],
       [ 1.41356495,  2.40240249,  2.23202325,  2.48086756,  2.26332859],
       [ 1.65225221,  1.86841405,  1.01490257,  2.33620675,  1.18172562],
       [ 1.62182895,  2.54432178,  1.51437552,  2.21838729,  1.4851096 ],
       [ 1.58699746,  1.44523498,  1.61865547,  1.39176714,  1.42772061],
       [ 2.20526567,  1.11685513,  1.10476865,  1.01504237,  1.88490241],
       [ 1.56585591,  1.07377296,  1.18898768,  2.58598248,  2.36831621],
       [ 1.9612958 ,  2.49555758,  1.62238496,  1.22090113,  1.66860271],
       [ 1.96960532,  1.48517229,  2.59543722,  1.203501  ,  1.15957537],
       [ 2.13228632,  2.36977041,  1.13682055,  1.94204969,  2.34659395],
       [ 1.64985908,  1.15692981,  2.52690039,  2.10381811,  1.54628545],
       [ 1.48936514,  2.32739927,  1.42094025,  1.45382446,  1.86069676],
       [ 1.91048368,  1.45537705,  1.00776089,  1.36865952,  2.50509662],
       [ 1.44026848,  1.4850282 ,  1.1

Now we have a problem if we do the same thing as last time because the whole matrix will sum to 1.
We want every row to sum to 1

In [8]:
#Solution

answerA = expA / expA.sum(axis = 1, keepdims=True)

Note for keepdims: If this is set to True, the axes which are reduced are left in the result as dimensions with size one. 
    With this option, the result will broadcast correctly against the input array.

In [9]:
answerA

array([[ 0.24475409,  0.16807439,  0.16795978,  0.17940456,  0.23980717],
       [ 0.1309804 ,  0.22260572,  0.20681844,  0.22987626,  0.20971918],
       [ 0.20515949,  0.23200022,  0.12602004,  0.29008585,  0.14673439],
       [ 0.17282875,  0.27113337,  0.16137807,  0.23640045,  0.15825937],
       [ 0.21243878,  0.19346216,  0.21667658,  0.18630484,  0.19111765],
       [ 0.30098479,  0.15243352,  0.1507839 ,  0.13853765,  0.25726014],
       [ 0.1782843 ,  0.12225701,  0.13537506,  0.29443327,  0.26965035],
       [ 0.21868126,  0.27825057,  0.18089325,  0.13612847,  0.18604646],
       [ 0.2341064 ,  0.17652691,  0.3084925 ,  0.14304759,  0.13782661],
       [ 0.21478538,  0.23870717,  0.11451203,  0.19562283,  0.2363726 ],
       [ 0.18364839,  0.12877966,  0.28127323,  0.23417928,  0.17211945],
       [ 0.17414942,  0.27213959,  0.16614859,  0.16999369,  0.21756871],
       [ 0.23164741,  0.17646543,  0.12219167,  0.16595087,  0.30374462],
       [ 0.18407047,  0.18979089,  0.1

In [10]:
# To check

answerA.sum(axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
# Check to see what denominator gives you

expA.sum(axis=1, keepdims=True)

array([[ 10.31300408],
       [ 10.79218684],
       [  8.05350119],
       [  9.38402313],
       [  7.47037567],
       [  7.32683423],
       [  8.78291524],
       [  8.96874219],
       [  8.4132912 ],
       [  9.92752092],
       [  8.98379284],
       [  8.55222587],
       [  8.24737777],
       [  7.82454948],
       [ 10.06195569],
       [  7.49807879],
       [  9.54995682],
       [  7.98837718],
       [  8.76692459],
       [  9.3736687 ],
       [ 10.12655269],
       [ 10.68410809],
       [  8.65540486],
       [  7.04700531],
       [ 11.28430789],
       [  8.17808714],
       [  6.90338361],
       [  8.67496663],
       [  7.26517875],
       [  8.05605829],
       [  7.52168229],
       [ 10.35307746],
       [  8.22871618],
       [  8.23218712],
       [  9.72432211],
       [  9.00660024],
       [  9.61052706],
       [  9.48364969],
       [  7.4386279 ],
       [  6.80234657],
       [ 10.37597841],
       [  6.93686785],
       [  9.44361006],
       [ 10

In [12]:
expA.sum(axis=1, keepdims=True).shape

(100L, 1L)